# Generated by Django 5.0.7 on 2024-12-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourservice', '0002_contactform_delete_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='name',
            new_name='fullname',
        ),
    ]
